name: DeployPages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1

      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo npm i yarn -g
          yarn
          yarn run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
